# Drop-in fragment for game-and-watch-retro-go-sd/linux/Makefile.cupcake
#
# Usage (from retro-go linux/ directory):
#   export CUPCAKE_PORT=/path/to/bart_simpson_cupcake_crisis_port
#   make -f Makefile.cupcake
#
# Copy assets to device:
#   /home/odroid/cupcake/sprites-color.png
#   /home/odroid/cupcake/sprites.png

TARGET = retro-go-cupcake

DEBUG = 1
OPT = -O0 -ggdb3
BUILD_DIR = build-cupcake

CUPCAKE_PORT ?= ../../retrofab-acclaim-cupcake-crisis-0.9.10/bart_simpson_cupcake_crisis_port

C_SOURCES = \
odroid_input.c \
odroid_netplay.c \
odroid_overlay.c \
odroid_sdcard.c \
odroid_system.c \
odroid_display.c \
odroid_audio.c \
gw_lcd.c \
porting.c \
$(CUPCAKE_PORT)/src/cupcake_game.c \
$(CUPCAKE_PORT)/src/cupcake_scoreboard.c \
$(CUPCAKE_PORT)/src/cupcake_timer.c \
$(CUPCAKE_PORT)/src/cupcake_rng.c \
$(CUPCAKE_PORT)/src/cupcake_state.c \
$(CUPCAKE_PORT)/platform/host_draw.c \
$(CUPCAKE_PORT)/platform/cupcake_input.c \
$(CUPCAKE_PORT)/platform/stb/stb_image_impl.c \
$(CUPCAKE_PORT)/platform/retrogo/main.c

CC = gcc
CFLAGS = -std=c99 -Wall -DTARGET_GNW -DLINUX_EMU \
	-I. \
	-I$(CUPCAKE_PORT)/src \
	-I$(CUPCAKE_PORT)/platform \
	-I$(CUPCAKE_PORT)/platform/stb \
	-I../Core/Inc/retro-go \
	-I../retro-go-stm32/components/odroid \
	$(shell sdl2-config --cflags 2>/dev/null) \
	$(OPT)

LIBS = -lm $(shell sdl2-config --libs 2>/dev/null)

OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))

all: $(BUILD_DIR)/$(TARGET).elf

$(BUILD_DIR)/%.o: %.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS)
	$(CC) $(OBJECTS) $(LIBS) -o $@

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

clean:
	rm -rf $(BUILD_DIR)

.PHONY: all clean
