#pragma once

typedef enum {
    ODROID_DISPLAY_SCALING_OFF = 0,
    ODROID_DISPLAY_SCALING_FIT,
    ODROID_DISPLAY_SCALING_FULL,
    ODROID_DISPLAY_SCALING_CUSTOM,
    ODROID_DISPLAY_SCALING_COUNT
} odroid_display_scaling_t;
