#!/usr/bin/env bash
# Generate linker PROVIDE() map from a built firmware.elf (symbol addresses only — no source needed).
#
# Usage:
#   tools/gen_overlay_imports.sh /path/to/firmware.elf > platform/gnw/firmware_imports.ld
#
# The elf must match the firmware you flash on the G&W (same version / commit).

set -euo pipefail

ELF="${1:?usage: $0 path/to/firmware.elf}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SYMS="${ROOT}/platform/gnw/firmware_symbols.txt"
NM="${NM:-arm-none-eabi-nm}"

if [ ! -f "$ELF" ]; then
  echo "missing elf: $ELF" >&2
  exit 1
fi

echo "/* Generated by tools/gen_overlay_imports.sh — do not edit by hand. */"
echo "/* Source elf: $ELF */"
echo "SECTIONS {"

missing=0
while IFS= read -r line || [ -n "$line" ]; do
  line="${line%%#*}"
  sym="$(echo "$line" | tr -d '[:space:]')"
  [ -z "$sym" ] && continue
  addr="$("$NM" -g "$ELF" 2>/dev/null | awk -v s="$sym" '$3==s && ($2=="T" || $2=="t" || $2=="W" || $2=="w") { print $1; exit }')"
  if [ -z "$addr" ]; then
    echo "/* MISSING: $sym */" >&2
    missing=$((missing + 1))
    continue
  fi
  echo "  PROVIDE($sym = 0x$addr);"
done < "$SYMS"

echo "}"

if [ "$missing" -gt 0 ]; then
  echo "warning: $missing symbol(s) not found in $ELF" >&2
  exit 1
fi
