#!/usr/bin/env python3

"""

Generate src/cupcake_sprites.h and src/cupcake_sprite_masks.h from sprites.json.



Triangle raster + largest connected bbox for rects; 1bpp row-major masks for blit

(same pixels as test/export_sprites.py — avoids atlas bbox overlap bleed).

"""

from __future__ import annotations



import json

import os

import sys



from PIL import Image



sys.path.insert(0, os.path.dirname(__file__))

from sprite_raster import (  # noqa: E402

    build_mask,

    collect_triangles,

    sprite_draw_bbox,

    pack_mask_bits,

)



ROOT = os.path.join(os.path.dirname(__file__), "..")

SPRITES_JSON = os.path.join(

    ROOT, "ignore", "har_extracted", "sim-acclaim-cupcakecrisis", "game", "sprites.json"

)

OUT_H = os.path.join(ROOT, "src", "cupcake_sprites.h")

OUT_MASK_H = os.path.join(ROOT, "src", "cupcake_sprite_masks.h")

ATLAS_PNG = os.path.join(ROOT, "assets", "sprites-color.png")

MAX_SPRITE_AREA = 120000

MIN_VISIBLE_PIXELS = 30





def c_array_bytes(data: bytes, per_line: int = 16) -> list[str]:

    lines: list[str] = []

    row: list[str] = []

    for i, b in enumerate(data):

        row.append(f"0x{b:02x}")

        if len(row) >= per_line:

            lines.append(", ".join(row))

            row = []

    if row:

        lines.append(", ".join(row))

    return lines





def main() -> None:

    with open(SPRITES_JSON, encoding="utf-8") as f:

        data = json.load(f)



    atlas = Image.open(ATLAS_PNG).convert("RGBA")

    tris = collect_triangles(data)

    bounds: dict[str, tuple[int, int, int, int]] = {}

    masks: dict[str, bytes] = {}



    for name, triangles in tris.items():

        mask = build_mask(atlas, triangles)

        box = sprite_draw_bbox(mask)

        if not box:

            continue

        x, y, w, h = box

        if w * h < MIN_VISIBLE_PIXELS:

            continue

        if w * h > MAX_SPRITE_AREA:

            continue

        bounds[name] = box

        masks[name] = pack_mask_bits(box, mask)[0]



    os.makedirs(os.path.dirname(OUT_H), exist_ok=True)

    lines = [

        "/* Auto-generated by tools/gen_sprites.py — triangle raster from sprites.json */",

        "/* Blit: sprites-color.png + per-sprite mask in cupcake_sprite_masks.h */",

        "#ifndef CUPCAKE_SPRITES_H_",

        "#define CUPCAKE_SPRITES_H_",

        "",

        "#define CUPCAKE_ATLAS_W 1024",

        "#define CUPCAKE_ATLAS_H 1024",

        "",

        "typedef struct {",

        "    const char *name;",

        "    int x, y, w, h;",

        "} cupcake_sprite_rect_t;",

        "",

        "static const cupcake_sprite_rect_t cupcake_sprites[] = {",

    ]

    for name in sorted(bounds.keys()):

        x, y, w, h = bounds[name]

        lines.append(f'    {{ "{name}", {x}, {y}, {w}, {h} }},')

    lines += [

        "};",

        "",

        f"#define CUPCAKE_SPRITE_COUNT {len(bounds)}",

        "",

        "static inline const cupcake_sprite_rect_t *cupcake_sprite_by_name(const char *name) {",

        "    for (unsigned i = 0; i < CUPCAKE_SPRITE_COUNT; i++) {",

        "        const char *a = cupcake_sprites[i].name, *b = name;",

        "        while (*a && *b && *a == *b) { a++; b++; }",

        "        if (!*a && !*b) return &cupcake_sprites[i];",

        "    }",

        "    return 0;",

        "}",

        "",

        "#endif",

    ]

    with open(OUT_H, "w", encoding="utf-8", newline="\n") as f:

        f.write("\n".join(lines) + "\n")



    mask_lines = [

        "/* Auto-generated by tools/gen_sprites.py — triangle masks for blit */",

        "#ifndef CUPCAKE_SPRITE_MASKS_H_",

        "#define CUPCAKE_SPRITE_MASKS_H_",

        "",

        "#include <stdint.h>",

        "",

        "#include \"cupcake_sprites.h\"",

        "",

        "typedef struct {",

        "    const char *name;",

        "    const uint8_t *bits;",

        "    unsigned nbytes;",

        "} cupcake_sprite_mask_t;",

        "",

    ]

    for name in sorted(bounds.keys()):

        safe = name.replace(".", "_")

        data = masks[name]

        mask_lines.append(f"static const uint8_t cupcake_mask_{safe}[] = {{")

        mask_lines.extend("    " + ln + "," for ln in c_array_bytes(data))

        mask_lines[-1] = mask_lines[-1].rstrip(",")

        mask_lines.append("};")

        mask_lines.append("")



    mask_lines.append("static const cupcake_sprite_mask_t cupcake_sprite_masks[] = {")

    for name in sorted(bounds.keys()):

        safe = name.replace(".", "_")

        nbytes = len(masks[name])

        mask_lines.append(

            f'    {{ "{name}", cupcake_mask_{safe}, {nbytes} }},'

        )

    mask_lines += [

        "};",

        "",

        f"#define CUPCAKE_SPRITE_MASK_COUNT {len(bounds)}",

        "",

        "static inline const cupcake_sprite_mask_t *cupcake_sprite_mask_by_name(const char *name) {",

        "    for (unsigned i = 0; i < CUPCAKE_SPRITE_MASK_COUNT; i++) {",

        "        const char *a = cupcake_sprite_masks[i].name, *b = name;",

        "        while (*a && *b && *a == *b) { a++; b++; }",

        "        if (!*a && !*b) return &cupcake_sprite_masks[i];",

        "    }",

        "    return 0;",

        "}",

        "",

        "static inline int cupcake_sprite_mask_get(const cupcake_sprite_mask_t *m,",

        "                                          int col, int row, int w, int h) {",

        "    if (!m || col < 0 || row < 0 || col >= w || row >= h)",

        "        return 0;",

        "    unsigned i = (unsigned)(row * w + col);",

        "    if ((i >> 3) >= m->nbytes)",

        "        return 0;",

        "    return (int)((m->bits[i >> 3] >> (7 - (i & 7))) & 1);",

        "}",

        "",

        "static inline int cupcake_sprite_mask_at(const char *name, int col, int row) {",

        "    const cupcake_sprite_rect_t *spr = cupcake_sprite_by_name(name);",

        "    const cupcake_sprite_mask_t *msk = cupcake_sprite_mask_by_name(name);",

        "    if (!spr || !msk)",

        "        return 1;",

        "    return cupcake_sprite_mask_get(msk, col, row, spr->w, spr->h);",

        "}",

        "",

        "#endif",

    ]

    with open(OUT_MASK_H, "w", encoding="utf-8", newline="\n") as f:

        f.write("\n".join(mask_lines) + "\n")



    total_mask = sum(len(v) for v in masks.values())

    print(f"Wrote {len(bounds)} sprites to {OUT_H}")

    print(f"Wrote {len(bounds)} masks ({total_mask} bytes) to {OUT_MASK_H}")

    for probe in ("cake04", "cake43", "maggie0", "bart2"):

        if probe in bounds:

            print(f"  {probe}: {bounds[probe]} mask {len(masks[probe])} bytes")





if __name__ == "__main__":

    main()

