#!/usr/bin/env python3
"""Generate src/cupcake/cupcake_demo.h from game/demo.model gameplay array."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEMO_MODEL = ROOT / "ignore" / "har_extracted" / "sim-acclaim-cupcakecrisis" / "game" / "demo.model"
OUT_H = ROOT / "src" / "cupcake" / "cupcake_demo.h"


def main() -> None:
    text = DEMO_MODEL.read_text(encoding="utf-8")
    rate_m = re.search(r'"rate"\s*:\s*([\d.]+)', text)
    rate = float(rate_m.group(1)) if rate_m else 0.25
    gp_m = re.search(r'"gameplay"\s*:\s*(\[\[.*\]\])', text, re.DOTALL)
    if not gp_m:
        raise SystemExit("gameplay array not found in demo.model")
    frames: list[list[str]] = json.loads(gp_m.group(1))

    name_set: set[str] = set()
    for fr in frames:
        name_set.update(fr)
    names_sorted = sorted(name_set)
    name_to_id = {n: i for i, n in enumerate(names_sorted)}

    lines = [
        "/* Auto-generated by tools/gen_demo_data.py from game/demo.model */",
        "#ifndef CUPCAKE_DEMO_H_",
        "#define CUPCAKE_DEMO_H_",
        "",
        f"#define CUPCAKE_DEMO_RATE_SEC {rate}",
        f"#define CUPCAKE_DEMO_FRAME_COUNT {len(frames)}",
        f"#define CUPCAKE_DEMO_NAME_COUNT {len(names_sorted)}",
        "",
        "static const char *const cupcake_demo_name_table[] = {",
    ]
    for n in names_sorted:
        lines.append(f'    "{n}",')
    lines += [
        "};",
        "",
        "typedef struct {",
        "    const unsigned char *sprite_ids;",
        "    unsigned char count;",
        "} cupcake_demo_frame_t;",
        "",
        "/* Per-frame sprite name indices into cupcake_demo_name_table */",
    ]

    id_arrays: list[str] = []
    for i, fr in enumerate(frames):
        arr = ", ".join(str(name_to_id[n]) for n in fr)
        id_arrays.append(f"static const unsigned char cupcake_demo_ids_{i}[] = {{ {arr} }};")
    lines.extend(id_arrays)
    lines.append("")
    lines.append("static const cupcake_demo_frame_t cupcake_demo_frames[] = {")
    for i, fr in enumerate(frames):
        lines.append(
            f"    {{ cupcake_demo_ids_{i}, {len(fr)} }},"
        )
    lines += [
        "};",
        "",
        "static inline const char *cupcake_demo_sprite_name(unsigned char id) {",
        "    if (id >= CUPCAKE_DEMO_NAME_COUNT)",
        "        return 0;",
        "    return cupcake_demo_name_table[id];",
        "}",
        "",
        "#endif",
    ]
    OUT_H.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_H} ({len(frames)} frames, {len(names_sorted)} unique sprites)")


if __name__ == "__main__":
    main()
