#!/usr/bin/env python3
"""Generate src/cupcake_sprite_lcd.h — mesh centroid -> LCD top-left (sprites.json)."""
from __future__ import annotations

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
from PIL import Image

from sprite_raster import (  # noqa: E402
    build_mask,
    collect_mesh_lcd_extents,
    collect_triangles,
    sprite_draw_bbox,
    mask_centroid,
)

ROOT = os.path.join(os.path.dirname(__file__), "..")
SPRITES_JSON = os.path.join(
    ROOT, "ignore", "har_extracted", "sim-acclaim-cupcakecrisis", "game", "sprites.json"
)
SPRITES_H = os.path.join(ROOT, "src", "cupcake_sprites.h")
OUT_H = os.path.join(ROOT, "src", "cupcake_sprite_lcd.h")
TUNE_TXT = os.path.join(ROOT, "assets", "lcd_tune.txt")

LCD_W = 1024
LCD_H = 800

# Fallback when assets/lcd_tune.txt is missing (prefer editing lcd_tune.txt + make gen).
MANUAL_LCD: dict[str, tuple[int, int]] = {
    "marge1": (0, 115),
    "maggie0": (705, 243),
    "maggie1": (724, 267),
    "maggie2": (855, 253),
    "maggie3": (720, 192),
}


def load_lcd_tune() -> dict[str, tuple[int, int]]:
    """Parse assets/lcd_tune.txt — same format as runtime live override."""
    out: dict[str, tuple[int, int]] = {}
    if not os.path.isfile(TUNE_TXT):
        return out
    with open(TUNE_TXT, encoding="utf-8") as f:
        for raw in f:
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) >= 3:
                out[parts[0]] = (int(parts[1]), int(parts[2]))
    return out


def load_sprite_sizes() -> dict[str, tuple[int, int]]:
    text = open(SPRITES_H, encoding="utf-8").read()
    sizes: dict[str, tuple[int, int]] = {}
    for m in re.finditer(r'\{\s*"([^"]+)",\s*\d+,\s*\d+,\s*(\d+),\s*(\d+)\s*\}', text):
        sizes[m.group(1)] = (int(m.group(2)), int(m.group(3)))
    return sizes


def main() -> None:
    data = json.load(open(SPRITES_JSON, encoding="utf-8"))
    verts = data["vertices"]
    n = len(verts) // 3
    xs = [verts[i * 3] for i in range(n)]
    ys = [verts[i * 3 + 1] for i in range(n)]
    xmin, xmax = min(xs), max(xs)
    ymin, ymax = min(ys), max(ys)

    atlas = Image.open(
        os.path.join(ROOT, "assets", "sprites-color.png")
    ).convert("RGBA")
    tris = collect_triangles(data)
    # Mesh X/Y linear map (RetroFab uses 3D camera; see docs/HOST_WEB.md for exact parity).
    extents = collect_mesh_lcd_extents(data, xmin, xmax, ymin, ymax, LCD_W, LCD_H)
    sizes = load_sprite_sizes()
    manual = {**MANUAL_LCD, **load_lcd_tune()}
    entries: list[tuple[str, int, int]] = []

    for name in sorted(extents.keys()):
        if name not in sizes:
            continue
        if name in manual:
            entries.append((name, *manual[name]))
            continue
        w, h = sizes[name]
        min_lx, min_ly, max_lx, max_ly = extents[name]
        mesh_cx = (min_lx + max_lx) // 2
        mesh_cy = (min_ly + max_ly) // 2
        lcd_x = mesh_cx - w // 2
        lcd_y = mesh_cy - h // 2
        if name in tris:
            mask = build_mask(atlas, tris[name])
            box = sprite_draw_bbox(mask)
            if box:
                bx, by, _, _ = box
                mc = mask_centroid(box, mask)
                if mc:
                    mask_cx, mask_cy = mc
                    lcd_x = int(mesh_cx - (mask_cx - bx) + 0.5)
                    lcd_y = int(mesh_cy - (mask_cy - by) + 0.5)
        lcd_x = max(0, min(LCD_W - w, lcd_x))
        lcd_y = max(0, min(LCD_H - h, lcd_y))
        entries.append((name, lcd_x, lcd_y))

    lines = [
        "/* Auto-generated by tools/gen_lcd_positions.py — mesh LCD bounds + mask anchor */",
        "#ifndef CUPCAKE_SPRITE_LCD_H_",
        "#define CUPCAKE_SPRITE_LCD_H_",
        "",
        "#include \"cupcake_sprites.h\"",
        "",
        "typedef struct {",
        "    const char *name;",
        "    int lcd_x, lcd_y;",
        "} cupcake_sprite_lcd_t;",
        "",
        "/* Atlas Y of marge1 body top before hair was included in the sprite rect. */",
        "#define CUPCAKE_MARGE1_LEGACY_ATLAS_Y 147",
        "",
        "/* Header/auto only: keep hair inside LCD when lcd_y is from cupcake_sprite_lcd.h. */",
        "static inline int cupcake_sprite_lcd_resolve_y(const char *name, int lcd_y)",
        "{\n"
        "    const cupcake_sprite_rect_t *spr;\n"
        "    int hair_rows;\n"
        "    int min_y;\n"
        "\n"
        "    if (!name || name[0] != 'm' || name[1] != 'a' || name[2] != 'r' || name[3] != 'g' ||\n"
        "        name[4] != 'e' || name[5] != '1' || name[6])\n"
        "        return lcd_y;\n"
        "    spr = cupcake_sprite_by_name(name);\n"
        "    if (!spr)\n"
        "        return lcd_y;\n"
        "    hair_rows = CUPCAKE_MARGE1_LEGACY_ATLAS_Y - spr->y;\n"
        "    if (hair_rows <= 0)\n"
        "        return lcd_y;\n"
        "    min_y = 1 - hair_rows;\n"
        "    if (lcd_y < min_y)\n"
        "        return min_y;\n"
        "    return lcd_y;\n"
        "}",
        "",
        "static const cupcake_sprite_lcd_t cupcake_sprite_lcd[] = {",
    ]
    for name, x, y in entries:
        lines.append(f'    {{ "{name}", {x}, {y} }},')
    lines += [
        "};",
        "",
        f"#define CUPCAKE_SPRITE_LCD_COUNT {len(entries)}",
        "",
        "static inline const cupcake_sprite_lcd_t *cupcake_sprite_lcd_by_name(const char *name) {",
        "    for (unsigned i = 0; i < CUPCAKE_SPRITE_LCD_COUNT; i++) {",
        "        const char *a = cupcake_sprite_lcd[i].name, *b = name;",
        "        while (*a && *b && *a == *b) { a++; b++; }",
        "        if (!*a && !*b) return &cupcake_sprite_lcd[i];",
        "    }",
        "    return 0;",
        "}",
        "",
        "#endif",
    ]
    with open(OUT_H, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {len(entries)} LCD positions to {OUT_H}")


if __name__ == "__main__":
    main()
