/* Auto-generated by tools/gen_lcd_positions.py — mesh LCD bounds + mask anchor */
#ifndef CUPCAKE_SPRITE_LCD_H_
#define CUPCAKE_SPRITE_LCD_H_

#include "cupcake_sprites.h"

typedef struct {
    const char *name;
    int lcd_x, lcd_y;
} cupcake_sprite_lcd_t;

/* Atlas Y of marge1 body top before hair was included in the sprite rect. */
#define CUPCAKE_MARGE1_LEGACY_ATLAS_Y 147

/* Header/auto only: keep hair inside LCD when lcd_y is from cupcake_sprite_lcd.h. */
static inline int cupcake_sprite_lcd_resolve_y(const char *name, int lcd_y)
{
    const cupcake_sprite_rect_t *spr;
    int hair_rows;
    int min_y;

    if (!name || name[0] != 'm' || name[1] != 'a' || name[2] != 'r' || name[3] != 'g' ||
        name[4] != 'e' || name[5] != '1' || name[6])
        return lcd_y;
    spr = cupcake_sprite_by_name(name);
    if (!spr)
        return lcd_y;
    hair_rows = CUPCAKE_MARGE1_LEGACY_ATLAS_Y - spr->y;
    if (hair_rows <= 0)
        return lcd_y;
    min_y = 1 - hair_rows;
    if (lcd_y < min_y)
        return min_y;
    return lcd_y;
}

static const cupcake_sprite_lcd_t cupcake_sprite_lcd[] = {
    { "bart0", 14, 576 },
    { "bart1", 98, 461 },
    { "bart2", 232, 390 },
    { "bart3", 369, 427 },
    { "bart4", 486, 504 },
    { "bart5", 582, 391 },
    { "bart6", 471, 70 },
    { "bart7", 111, 417 },
    { "bart8", 511, 441 },
    { "bart9", 164, 669 },
    { "cake0", 32, 643 },
    { "cake01", 17, 503 },
    { "cake02", 90, 512 },
    { "cake03", 54, 503 },
    { "cake04", 81, 464 },
    { "cake05", 46, 452 },
    { "cake1", 216, 206 },
    { "cake11", 117, 359 },
    { "cake12", 172, 365 },
    { "cake13", 178, 315 },
    { "cake14", 123, 308 },
    { "cake15", 148, 260 },
    { "cake2", 331, 208 },
    { "cake21", 228, 324 },
    { "cake22", 283, 338 },
    { "cake23", 297, 288 },
    { "cake24", 238, 287 },
    { "cake25", 278, 247 },
    { "cake3", 449, 199 },
    { "cake31", 379, 360 },
    { "cake32", 445, 365 },
    { "cake33", 450, 311 },
    { "cake34", 397, 318 },
    { "cake35", 419, 270 },
    { "cake4", 500, 239 },
    { "cake41", 513, 399 },
    { "cake42", 564, 398 },
    { "cake43", 553, 351 },
    { "cake44", 506, 351 },
    { "cake45", 516, 304 },
    { "cake5", 279, 126 },
    { "cake6", 394, 131 },
    { "cake7", 509, 119 },
    { "cake8", 616, 112 },
    { "cake9", 427, 695 },
    { "couch0", 755, 149 },
    { "couch1", 812, 334 },
    { "couch2", 758, 372 },
    { "couch3", 618, 628 },
    { "couch4", 725, 517 },
    { "digit00", 936, 25 },
    { "digit01", 959, 26 },
    { "digit03", 958, 67 },
    { "digit04", 932, 78 },
    { "digit05", 929, 66 },
    { "digit06", 932, 22 },
    { "digit10", 876, 23 },
    { "digit11", 900, 26 },
    { "digit13", 899, 67 },
    { "digit14", 874, 77 },
    { "digit15", 871, 66 },
    { "digit16", 872, 20 },
    { "digit20", 820, 24 },
    { "digit21", 842, 26 },
    { "digit22", 826, 52 },
    { "digit23", 841, 67 },
    { "digit24", 817, 78 },
    { "digit25", 815, 66 },
    { "digit26", 816, 20 },
    { "digit30", 762, 23 },
    { "digit31", 784, 26 },
    { "digit32", 766, 52 },
    { "digit33", 783, 67 },
    { "digit34", 760, 78 },
    { "digit35", 756, 66 },
    { "digit36", 758, 20 },
    { "digit40", 701, 21 },
    { "digit41", 726, 26 },
    { "digit42", 708, 53 },
    { "digit43", 725, 67 },
    { "digit44", 701, 78 },
    { "digit45", 697, 66 },
    { "digit46", 699, 18 },
    { "maggie0", 705, 243 },
    { "maggie1", 724, 267 },
    { "maggie2", 855, 253 },
    { "maggie3", 720, 192 },
    { "marge1", 0, 115 },
    { "miss1", 13, 12 },
    { "miss2", 99, 12 },
    { "miss3", 208, 20 },
    { "pacifier1", 419, 151 },
    { "pacifier2", 338, 253 },
};

#define CUPCAKE_SPRITE_LCD_COUNT 93

static inline const cupcake_sprite_lcd_t *cupcake_sprite_lcd_by_name(const char *name) {
    for (unsigned i = 0; i < CUPCAKE_SPRITE_LCD_COUNT; i++) {
        const char *a = cupcake_sprite_lcd[i].name, *b = name;
        while (*a && *b && *a == *b) { a++; b++; }
        if (!*a && !*b) return &cupcake_sprite_lcd[i];
    }
    return 0;
}

#endif
