/* Auto-generated by tools/gen_lcd_positions.py — mesh LCD bounds + mask anchor */
#ifndef CUPCAKE_SPRITE_LCD_H_
#define CUPCAKE_SPRITE_LCD_H_

#include "cupcake_sprites.h"

typedef struct {
    const char *name;
    int lcd_x, lcd_y;
} cupcake_sprite_lcd_t;

/* Atlas Y of marge1 body top before hair was included in the sprite rect. */
#define CUPCAKE_MARGE1_LEGACY_ATLAS_Y 147

/* Header/auto only: keep hair inside LCD when lcd_y is from cupcake_sprite_lcd.h. */
static inline int cupcake_sprite_lcd_resolve_y(const char *name, int lcd_y)
{
    const cupcake_sprite_rect_t *spr;
    int hair_rows;
    int min_y;

    if (!name || name[0] != 'm' || name[1] != 'a' || name[2] != 'r' || name[3] != 'g' ||
        name[4] != 'e' || name[5] != '1' || name[6])
        return lcd_y;
    spr = cupcake_sprite_by_name(name);
    if (!spr)
        return lcd_y;
    hair_rows = CUPCAKE_MARGE1_LEGACY_ATLAS_Y - spr->y;
    if (hair_rows <= 0)
        return lcd_y;
    min_y = 1 - hair_rows;
    if (lcd_y < min_y)
        return min_y;
    return lcd_y;
}

static const cupcake_sprite_lcd_t cupcake_sprite_lcd[] = {
    { "bart0", 26, 540 },
    { "bart1", 110, 443 },
    { "bart2", 235, 368 },
    { "bart3", 360, 395 },
    { "bart4", 485, 482 },      
    { "bart5", 585, 382 },  
    { "bart6", 520, 12 },
    { "bart7", 116, 395 },
    { "bart8", 514, 430 },
    { "bart9", 167, 650 },
    { "cake0", 42, 646 },
    { "cake01", 20, 506 },
    { "cake02", 93, 515 },
    { "cake03", 57, 506 },
    { "cake04", 84, 467 },
    { "cake05", 49, 455 },
    { "cake1", 219, 209 },
    { "cake11", 120, 362 },
    { "cake12", 175, 368 },
    { "cake13", 181, 318 },
    { "cake14", 126, 311 },
    { "cake15", 151, 263 },
    { "cake2", 334, 211 },
    { "cake21", 231, 327 },
    { "cake22", 286, 341 },
    { "cake23", 300, 291 },
    { "cake24", 241, 290 },
    { "cake25", 281, 250 },
    { "cake3", 452, 202 },
    { "cake31", 382, 363 },
    { "cake32", 448, 368 },
    { "cake33", 453, 314 },
    { "cake34", 400, 321 },
    { "cake35", 422, 273 },
    { "cake4", 503, 242 },
    { "cake41", 516, 402 },
    { "cake42", 567, 401 },
    { "cake43", 556, 348 },
    { "cake44", 509, 354 },
    { "cake45", 519, 307 },
    { "cake5", 282, 129 },
    { "cake6", 397, 134 },
    { "cake7", 512, 122 },
    { "cake8", 619, 115 },
    { "cake9", 430, 698 },
    { "couch0", 758, 152 },
    { "couch1", 816, 337 },
    { "couch2", 761, 375 },
    { "couch3", 621, 631 },
    { "couch4", 728, 520 },
    { "digit00", 939, 28 },
    { "digit01", 962, 29 },
    { "digit03", 961, 70 },
    { "digit04", 935, 81 },
    { "digit05", 932, 69 },
    { "digit06", 935, 25 },
    { "digit10", 879, 26 },
    { "digit11", 903, 29 },
    { "digit13", 902, 70 },
    { "digit14", 877, 80 },
    { "digit15", 874, 69 },
    { "digit16", 875, 23 },
    { "digit20", 823, 27 },
    { "digit21", 845, 29 },
    { "digit22", 829, 55 },
    { "digit23", 844, 70 },
    { "digit24", 820, 81 },
    { "digit25", 818, 69 },
    { "digit26", 819, 23 },
    { "digit30", 765, 26 },
    { "digit31", 787, 29 },
    { "digit32", 769, 55 },
    { "digit33", 786, 70 },
    { "digit34", 763, 81 },
    { "digit35", 759, 69 },
    { "digit36", 761, 23 },
    { "digit40", 704, 24 },
    { "digit41", 729, 29 },
    { "digit42", 711, 56 },
    { "digit43", 728, 70 },
    { "digit44", 704, 81 },
    { "digit45", 700, 69 },
    { "digit46", 702, 21 },
    { "maggie0", 705, 243 },
    { "maggie1", 724, 267 },
    { "maggie2", 855, 253 },
    { "maggie3", 720, 192 },
    { "marge1", 0, 115 },
    { "miss1", 16, 15 },
    { "miss2", 102, 15 },
    { "miss3", 235, 34 },
    { "pacifier1", 434, 149 },
    { "pacifier2", 343, 252 },
};

#define CUPCAKE_SPRITE_LCD_COUNT 93

static inline const cupcake_sprite_lcd_t *cupcake_sprite_lcd_by_name(const char *name) {
    for (unsigned i = 0; i < CUPCAKE_SPRITE_LCD_COUNT; i++) {
        const char *a = cupcake_sprite_lcd[i].name, *b = name;
        while (*a && *b && *a == *b) { a++; b++; }
        if (!*a && !*b) return &cupcake_sprite_lcd[i];
    }
    return 0;
}

#endif
