/* Auto-generated by tools/gen_sprites.py — triangle raster from sprites.json */
/* Blit: sprites-color.png + per-sprite mask in cupcake_sprite_masks.h */
#ifndef CUPCAKE_SPRITES_H_
#define CUPCAKE_SPRITES_H_

#define CUPCAKE_ATLAS_W 1024
#define CUPCAKE_ATLAS_H 1024

typedef struct {
    const char *name;
    int x, y, w, h;
} cupcake_sprite_rect_t;

static const cupcake_sprite_rect_t cupcake_sprites[] = {
    { "bart0", 28, 541, 119, 61 },
    { "bart1", 112, 443, 131, 238 },
    { "bart2", 237, 369, 114, 268 },
    { "bart3", 363, 391, 133, 273 },
    { "bart4", 484, 482, 111, 245 },
    { "bart5", 585, 381, 157, 231 },
    { "bart6", 546, 14, 175, 384 },
    { "bart7", 117, 396, 92, 71 },
    { "bart8", 517, 431, 93, 42 },
    { "bart9", 170, 650, 284, 102 },
    { "cake0", 69, 692, 81, 60 },
    { "cake01", 28, 497, 32, 35 },
    { "cake02", 93, 501, 32, 36 },
    { "cake03", 60, 483, 32, 34 },
    { "cake04", 83, 455, 36, 35 },
    { "cake05", 49, 440, 33, 34 },
    { "cake1", 216, 204, 40, 42 },
    { "cake11", 126, 355, 39, 39 },
    { "cake12", 172, 358, 39, 37 },
    { "cake13", 178, 313, 36, 39 },
    { "cake14", 137, 310, 36, 39 },
    { "cake15", 163, 272, 39, 40 },
    { "cake2", 342, 190, 39, 39 },
    { "cake21", 240, 328, 43, 41 },
    { "cake22", 286, 332, 38, 39 },
    { "cake23", 300, 290, 37, 39 },
    { "cake24", 252, 285, 42, 39 },
    { "cake25", 281, 248, 39, 40 },
    { "cake3", 454, 186, 39, 41 },
    { "cake31", 395, 358, 37, 38 },
    { "cake32", 438, 357, 39, 39 },
    { "cake33", 448, 315, 37, 39 },
    { "cake34", 410, 317, 37, 38 },
    { "cake35", 421, 273, 40, 42 },
    { "cake4", 513, 248, 37, 38 },
    { "cake41", 525, 392, 36, 38 },
    { "cake42", 565, 391, 43, 42 },
    { "cake43", 554, 343, 43, 46 },
    { "cake44", 514, 347, 38, 41 },
    { "cake45", 532, 308, 38, 38 },
    { "cake5", 303, 139, 40, 38 },
    { "cake6", 405, 115, 38, 40 },
    { "cake7", 513, 116, 39, 38 },
    { "cake8", 621, 106, 39, 38 },
    { "cake9", 447, 693, 80, 67 },
    { "couch0", 757, 114, 251, 116 },
    { "couch1", 815, 358, 190, 382 },
    { "couch2", 756, 338, 170, 396 },
    { "couch3", 620, 602, 104, 142 },
    { "couch4", 726, 488, 97, 211 },
    { "digit00", 940, 25, 35, 15 },
    { "digit01", 966, 32, 14, 27 },
    { "digit03", 964, 63, 13, 27 },
    { "digit04", 936, 82, 34, 14 },
    { "digit05", 929, 62, 16, 29 },
    { "digit06", 932, 29, 15, 30 },
    { "digit10", 882, 25, 36, 15 },
    { "digit11", 908, 32, 15, 27 },
    { "digit13", 906, 63, 14, 27 },
    { "digit14", 878, 82, 35, 14 },
    { "digit15", 871, 62, 16, 29 },
    { "digit16", 874, 29, 15, 30 },
    { "digit20", 825, 25, 35, 15 },
    { "digit21", 850, 32, 15, 27 },
    { "digit22", 828, 53, 23, 15 },
    { "digit23", 848, 63, 14, 27 },
    { "digit24", 821, 82, 34, 14 },
    { "digit25", 814, 62, 15, 29 },
    { "digit26", 817, 28, 14, 31 },
    { "digit30", 767, 25, 35, 15 },
    { "digit31", 793, 32, 14, 27 },
    { "digit32", 770, 53, 24, 15 },
    { "digit33", 791, 63, 13, 27 },
    { "digit34", 763, 82, 35, 14 },
    { "digit35", 756, 62, 16, 29 },
    { "digit36", 759, 29, 15, 30 },
    { "digit40", 708, 25, 36, 15 },
    { "digit41", 734, 32, 15, 27 },
    { "digit42", 711, 53, 24, 15 },
    { "digit43", 732, 63, 14, 27 },
    { "digit44", 704, 82, 35, 14 },
    { "digit45", 697, 62, 16, 29 },
    { "digit46", 701, 29, 14, 30 },
    { "maggie0", 708, 243, 153, 227 },
    { "maggie1", 728, 265, 37, 37 },
    { "maggie2", 855, 250, 108, 65 },
    { "maggie3", 725, 193, 64, 67 },
    { "marge1", 1, 119, 117, 384 },
    { "miss1", 25, 10, 71, 90 },
    { "miss2", 103, 10, 70, 90 },
    { "miss3", 252, 15, 178, 48 },
    { "pacifier1", 399, 153, 57, 56 },
    { "pacifier2", 332, 266, 44, 99 },
};

#define CUPCAKE_SPRITE_COUNT 93

static inline const cupcake_sprite_rect_t *cupcake_sprite_by_name(const char *name) {
    for (unsigned i = 0; i < CUPCAKE_SPRITE_COUNT; i++) {
        const char *a = cupcake_sprites[i].name, *b = name;
        while (*a && *b && *a == *b) { a++; b++; }
        if (!*a && !*b) return &cupcake_sprites[i];
    }
    return 0;
}

#endif
